config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users

  resources :users, only: [:index, :show]
  resources :messages, only: [:create]
  resources :classrooms
  get '/invite/:classroom_id/:user_id' => 'classrooms#invite_user'

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  include ApplicationHelper
  has_many :messages

  belongs_to :user
  has_many :memberships
  has_many :users, through: :memberships 

  validates :name, presence: true
  validates :description, presence: true
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :classroom
end

app/models/message.rb
class Message < ApplicationRecord
  include ApplicationHelper
  belongs_to :user
  belongs_to :classroom

  validates :content, presence: true
  validates :user_id, presence: true
  validates :classroom_id, presence: true

  scope :recent, -> { order(:created_at).last(50) }
end

app/models/user.rb
class User < ApplicationRecord  
  has_many :messages
  has_many :memberships
  has_many :classrooms
  has_many :classrooms, through: :memberships

  validates :name, :uniqueness => {:case_sensitive => false}
  validates :email, presence: true, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def can_delete?(classroom)
    self == classroom.user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    notify_of_activity(resource.email)
  end

  def after_sign_up_path_for(resource)
    notify_of_activity(resource.email)
  end

  def notify_of_activity(email)
    ApplicationMailer.notify_of_usage(email).deliver_now
    classrooms_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_filter :find_classroom, only: [:show, :join_classroom, :destroy, :invite_user, :create_classroom_membership]
  before_filter :get_messages, only: [:show]

  def get_messages
    @messages = @classroom.messages
    @message  = current_user.messages.build
  end

  def find_classroom
    id = params[:id] || params[:classroom_id]
    @classroom = Classroom.find(id)
  end

  def index
    @classrooms = Classroom.all
    joined = current_user.memberships.pluck(:classroom_id)
    owned = current_user.classrooms.where(user_id: current_user.id).pluck(:id)
    @joined_classrooms = Classroom.where(id: joined + owned)
  end

  def new
    @classroom = current_user.classrooms.new
  end

  def show
    create_classroom_membership(current_user)
    members_ids = Membership.where(classroom_id: @classroom.id).pluck(:user_id).uniq << current_user.id
    @invitable_users = User.where.not(id: members_ids)
    @current_members = User.where(id: members_ids)
  end 

  def invite_user
    user = User.find(params[:user_id])
    create_classroom_membership(user)
    ApplicationMailer.send_classroom_invite(user.id, @classroom.id).deliver_now
    flash[:notice] = "Successfully invited #{user.name}."
    redirect_to @classroom
  end

  def create
    @classroom = Classroom.create(classroom_params.merge(user_id: current_user.id))

    if @classroom.save
      create_classroom_membership(current_user)
      flash[:notice] = "classroom created successfully."
      redirect_to classrooms_path
    else
      render :new
    end
  end

  def destroy
    if @classroom.destroy
      flash[:notice] = "classroom deleted successfully"
    else
      flash[:error] = "classroom delete failed"
    end

    redirect_to classrooms_path
  end

  private

  def create_classroom_membership(user)
    if !user.classrooms.include?(@classroom)
      Membership.create!(classroom_id: @classroom.id, user_id: user.id)
    end
  end

  def classroom_params
    params.require(:classroom).permit(:name, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    message = current_user.messages.build(message_params)
    data = {}
    if message.save
      data[:html] = render partial: 'messages/message', locals: { message_content: message.content, sender_name: message.user.name}
      data[:classroom_id] = message_params['classroom_id']
      data[:sender_id] = message.user.id
      data[:current_user_id] = current_user.id

      ActionCable.server.broadcast "classroom_channel", data
    else
      render 'index'
    end
  end
 
  private

  def message_params
    params.require(:message).permit(:content, :classroom_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path, alert: 'Access denied.'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_time(time)
    time_ago_in_words(time)
  end


  def user_name
    if self.user
      self.user.name
    else
      '[deleted]'
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/classrooms/_classrooms.html.erb
<% classrooms.each do |classroom| %>
  <tr>
    <td>
      <%= classroom.name%>
    </td>
    <td><%= "#{classroom.description[0..25]}.." %></td>
    
    <td><%= format_time(classroom.created_at) %></td>

    <td><%= classroom.user_name %></td>
    <td>
      <% if current_user.can_delete?(classroom) %>
        <%= link_to 'Delete', classroom_path(classroom),
          method: :delete,
          class: 'btn btn-outline-danger btn-sm',
          data: {confirm: 'Are you sure you want to delete this classroom?'} %>
      <% end %>
    </td>
    <td>
      <a href=<%= classroom_path(classroom) %>>
        <div class='btn btn-primary'>Join classroom</div>
      </a>
    </td>
  </tr>
<% end %>

app/views/classrooms/index.html.erb
<p class="lead text-right">
  <%= link_to 'Create new classroom', new_classroom_path, class: 'btn btn-outline-primary' %>
</p>

<table class="table table-hover">
  <h2>Joined Classrooms</h2>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Created on</th>
      <th>Owner</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% if @joined_classrooms.present? %>
      <%= render partial: "classrooms", locals: {classrooms: @joined_classrooms} %>
    <% else %>
      <tr>
        <td colspan=5 class="empty-classroom-td">
          You have yet to join a classroom!
        </td>
      <tr>
    <% end %>
    
    <tr>
      <td colspan=5 class="empty-classroom-td text-left">
        <h2>Other Classrooms</h2>
      </td>
    <tr>

    <% if @classrooms.present? %>
      <%= render partial: "classrooms", locals: {classrooms: @classrooms} %>
    <% else %>
      <tr>
        <td colspan=5 class="empty-classroom-td">
          There are no classrooms yet.
          <%= link_to 'Create one', new_classroom_path, class: 'btn btn-outline-success btn-sm' %>
        </td>
      <tr>
    <% end %>
  </tbody>
</table>

app/views/classrooms/new.html.erb
<h3>Create new classroom</h3>

<div class="classroom-create-form">
	<%= form_for @classroom do |f| %>
	  <%= render 'share/form_errors', form: f.object %>
	  <hr>
	  <div class="form-group">
	    <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Classroom Name" %>
	    <%= f.text_area :description, class: 'form-control', placeholder: "What will be intended classroom discussion?", cols: 30 %>
	  </div>

	  <%= link_to 'Back', classrooms_path, class: 'btn btn-secondary' %>
	  <%= f.submit 'Create', class: 'btn btn-primary' %>
	<% end %>
</div>

app/views/classrooms/show.html.erb
<div class="row">
  <div class="col-lg-3">
    <div class='btn btn-default'>
      <%= link_to "Go Back", classrooms_path %>
    </div>
    <hr>
    <span class='badge badge-primary classroom-name-title'>
      <%= @classroom.name %>
    </span>
  </div>  
  <div class="col-lg-9 text-left">
    <h2>Class Description</h2>
    <h6><%= @classroom.description %></h6>
  </div>
</div>

<div class='chatroom-container'>
  <div class='chat-box'>
    <div id="messages" class="messages">
      <div id="messages-table" class="messages-table" data-classroom=<%= "classroom-#{@classroom.id}" %> >
        <% if @messages.any? %>

          <% @messages.each do |message| %>
            <span data-sender-true=<%= current_user.id == message.user_id %>>
              <%= render partial: 'messages/message', locals: {message_content: message.content, sender_name: message.user ? message.user.name : 'deleted' }%>
            </span>

          <% end %>
        <% else %>
          <div class='alert alert-info classroom-message-empty-notice' role='alert'>
            No conversations yet!
          </div>
        <% end %>
      </div>
    </div>

    <div class='keyboard-container'>
      <div class='message-input'>
        <%= form_for(@message, remote: true) do |f| %>
          <%= f.text_field :content %>
          <%= f.hidden_field :classroom_id, :value => @classroom.id %>
          <%= f.submit 'Send', placeholder: 'Write message..', class: 'submit' %>
        <% end %>
      </div>
    </div>
  </div>

  <div class='user-box'>
    <div class='user-content'>

      <h5>Joined</h5>
      <% @current_members.each do |user| %>
        <div class='badge badge-primary'>
          <span><%= user.name %></span>
        </div>
      <% end %>
      <hr>
      <h5>Invite Others</h5>
      <% @invitable_users.each do |user| %>
        <a href="/invite/<%= @classroom.id %>/<%=user.id %>">
          <div class='badge badge-default'>
            <span>Invite <%= user.name %></span>
          </div>
        </a>
      <% end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h3>Welcome</h3>
<p>
There are total
<%= User.count %> registered <%= link_to 'users', users_path %> like you.
Enjoy the talk!
</p>
<hr/>
<%= link_to 'Get Started', classrooms_path, class: 'btn btn-outline-success btn-block' %>

app/views/layouts/_flash_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="header-container">
  <div class="items-container">
    <%= link_to (image_tag asset_url('guild_logo.png')), root_path, class: 'navbar-logo' %>

    <div class="nav-links-mobile-wrapper">
      <% if current_user %>
        <span class="nav-item <%= controller_name == 'classrooms' ? 'active-nav' : '' %>" ><%= link_to 'Classrooms', classrooms_path, class: 'nav-link' %></span>
      <% end %>
    
      <% if user_signed_in? %>
        <span class="nav-item"><%= link_to 'Account', edit_user_registration_path, class: 'nav-link' %></span>
        <span class="nav-item"><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></span>
        <span class='welcome-name'><%= "Welcome, #{current_user.name}" %></span>
      <% else %>
        <span class="nav-item"><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></span>
        <span class="nav-item"><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></span>
      <% end %>
    </div>

    <div class="menu-toggle-wrapper">
      <div id="menu-toggle">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Guild Messenger" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Guild Messenger" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'guild_icon.ico' %>
    <%= render 'share/analytics' if  Rails.env.production? %>
  </head>
  
  <body>
    <%= render 'layouts/navigation' %>
    <div id="main">
      <div class='content-container'>
        <div class='content-wrapper'>
          <%= render 'layouts/flash_messages' %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <div class="message-user">
    <%= sender_name %>:
  </div>
  <div class="message-content">
    <%= message_content %>
  </div>
</div>

app/views/share/_form_errors.html.erb
<% if form.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h5><%= pluralize(form.errors.count, "error") %> on form found.</h5>

    <ul>
      <% form.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
  </div>
  <div class="row">
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>